server:
  port: 9001

spring:
  application:
    name: PRODUCT-SERVICE
    
  data:
    mongodb: 
      host: localhost
      port: 27017
      database: shopping

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
